name: GitHub Pages

on:
  push:
    branches:
      - dev-actions-fix
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    permissions:
      contents: write

    concurrency:
      group: cicd-docs

    steps:
      - name: Checkout Git submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -r docs/requirements.txt
          pip install -e .

      - name: Build Sphinx documentation
        run: |
          cd docs/
          sphinx-build -M clean ./ build
          sphinx-build -M html ./ build

      - name: Deploy documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/dev-actions-fix' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html
