name: GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: cicd-docs
    steps:
      - name: Checkout Git submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Copy Python files
        run: |
          sudo mkdir -p docs/ebyte_e32
          sudo cp ebyte_e32/*.py docs/ebyte_e32/

      - name: Build Sphinx documentation
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"

      - name: Deploy documentation to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html