name: Release On Tag

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout Git submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }} Release

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Minify Module
        run: |
          python compress.py

      - name: Prepare for Compilation
        run: |
          mkdir -p output-py/ebyte_e32
          mkdir output-mpy
          mkdir output-min-mpy
          cp -r ./ebyte_e32 ./output-py

      - name: Compiling Normal Module
        uses: addnab/docker-run-action@v3
        with:
          registry: registry.hub.docker.com
          image: aziascreations/cpy-mpy-cross:8.1.0
          options: -v ${{ github.workspace }}/output-py:/data/input -v ${{ github.workspace }}/output-mpy:/data/output -e MPY_CROSS_EXTRA_ARGS=-O1
          run: |
            /entrypoint.sh

      - name: Compiling Minified Module
        uses: addnab/docker-run-action@v3
        with:
          registry: registry.hub.docker.com
          image: aziascreations/cpy-mpy-cross:8.1.0
          options: -v ${{ github.workspace }}/output-min:/data/input -v ${{ github.workspace }}/output-min-mpy:/data/output -e MPY_CROSS_EXTRA_ARGS=-O1
          run: |
            /entrypoint.sh

      - name: Make ZIP Archives
        run: |
          echo "Doing regular files..."
          cd output-py
          zip -r -9 ../nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_py.zip ebyte_e32
          cd ..
          
          echo "Doing minified files..."
          cd output-min
          zip -r -9 ../nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_py-min.zip ebyte_e32
          cd ..
          
          echo "Doing compiled files..."
          cd output-mpy
          zip -r -9 ../nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_mpy-8.zip ebyte_e32
          cd ..
          
          echo "Doing compiled minified files..."
          cd output-min-mpy
          zip -r -9 ../nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_mpy-8-min.zip ebyte_e32
          cd ..

      - name: Upload Release Asset - Raw Python Files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_py.zip
          asset_name: nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_py.zip
          asset_content_type: application/zip

      - name: Upload Release Asset - Minified Python Files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_py-min.zip
          asset_name: nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_py-min.zip
          asset_content_type: application/zip

      - name: Upload Release Asset - Compiled Python Files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_mpy-8.zip
          asset_name: nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_mpy-8.zip
          asset_content_type: application/zip

      - name: Upload Release Asset - Compiled Minified Python Files
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_mpy-8-min.zip
          asset_name: nibblepoker-circuitpython-e32-driver_${{ github.ref_name }}_mpy-8-min.zip
          asset_content_type: application/zip
